- name: create system user
  user:
    name: expense
    system: true
    home: /app
    shell: /sbin/nologin
    comment: expense system user

- name: remove app directory
  file: 
    path: /app
    state: absent

- name: delete {{ component }}.zip in tmp directory
  file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: create app directory
  file:
    path: /app
    state: directory

- name: download {{ component }} zip file
  get_url:
    url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-{{ component }}-v3.tar.gz
    dest: /tmp/"{{ component }}".tar.gz

- name: unzip {{ component }} file
  unarchive:
    src: /tmp/{{ component }}.tar.gz
    dest: /app 
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app